/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.oss.frame.form.user;

import com.java.oss.classes.Product;
import com.java.oss.classes.User;
import com.java.oss.frame.LoginPortal;
import com.java.oss.frame.form.product.ViewProductListRow;
import com.java.oss.utils.Utils;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;

/**
 *
 * @author aashish
 */
public class UserListPanel extends javax.swing.JPanel {

    private JPanel parentPanel;
    /**
     * Creates new form UserListPanel
     */
    public UserListPanel(JPanel parentPanel) {
        this.parentPanel = parentPanel;
        initComponents();
        List<User> userList = getUserList();
        setListView(userList);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(700, 400));
        setMinimumSize(new java.awt.Dimension(700, 400));

        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<User> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private List<User> getUserList() {
        
        List<User> userList = new ArrayList<>();
        try {
            // TODO add your handling code here:
            
            BufferedReader bw = new BufferedReader(new FileReader(Utils.U_FILENAME));
            String line = bw.readLine();
            while(line != null) {
                String[] userInfoArr = line.split(",");
                
                line = bw.readLine();
                User user = new User();
                user.setId(Integer.parseInt(userInfoArr[User.ID]));
                user.setFullName(userInfoArr[User.FULL_NAME]);
                user.setAddress(userInfoArr[User.ADDRESS]);
                user.setEmail(userInfoArr[User.EMAIL]);
                user.setPhone(userInfoArr[User.PHONE]);
                user.setUsername(userInfoArr[User.USERNAME]);
                user.setPassword(userInfoArr[User.PASSWORD]);
                try {
                    user.setRole(Integer.parseInt(userInfoArr[User.ROLE]));
                }catch(NumberFormatException e) {
                    user.setRole(User.ROLE_CUSTOMER);
                }
                userList.add(user);
            }
                
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        return userList;
    }

    private void setListView(List<User> userList) {
          DefaultListModel<User> defaultListModel = new DefaultListModel<>();
        
        for(User user: userList) {
            defaultListModel.addElement(user);
            
        }
        
        jList1.setModel(defaultListModel);
        jList1.setCellRenderer(new ViewUserList()); 
    
    }
}
